server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:./data/assurancedb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: q8NfV4m2Zx7Lr1Tj9YpC3wHs6BdKe0AuMn5QvRgUaR8=
    expiration-ms: 86400000
